# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: doc/source/conf.py

build:
  image: latest
  apt_packages:
    - libdbus-1-dev

python:
   install:
   - requirements: requirements.txt
