language: python
dist: xenial
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - dbus-x11
      - libdbus-glib-1-dev

install:
  - pip install -r requirements.txt
  - pip install .  # See setup.py
  - pip install coveralls

script:
  - dbus-launch --exit-with-session nosetests -v -d --with-coverage --cover-package=tracer --cover-inclusive

notifications:
  email: false

after_success:
  coveralls
