language: python
dist: trusty
sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
    - sudo apt-get update
    - >
      sudo apt-get -yq install
      libdbus-1-dev
      libdbus-glib-1-dev
      dbus

install:
  # These first 2 lines are a nasty Travis hack, see https://github.com/travis-ci/travis-ci/issues/653
  - which python3.3-config && sed -i "s|not getvar('Py_ENABLE_SHARED')|True|" $(which python3.3-config) || true
  - sed -i "s|not getvar('Py_ENABLE_SHARED')|True|" $(which python)-config || true

  - pip install -r requirements.txt
  - pip install .  # See setup.py
  - pip install coveralls

script: nosetests -v -d --with-coverage --cover-package=tracer --cover-inclusive

notifications:
  email: false

after_success:
  coveralls
